name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - "features/**"
jobs:
  example_matrix:
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/setup-node@v3
      - name: Starting Node.js ${{ matrix.version }}
        with:
          node-version: ${{ matrix.version }}
      - name: Install modules
        run: npm install
      - name: Start tests
        run: npm run jest
